#!/bin/bash

# Aliases

alias rm='rm -i'


# VTE Configuration for Tilix

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi


# Java Configuration

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk


# Path

export PATH=$JAVA_HOME/bin:$PATH

