#!/bin/bash

# Variables

JAVA8=$(ls -1 /Library/Java/JavaVirtualMachines | grep "jdk1.8.*.jdk")


# Exports

export JAVA_HOME=/Library/Java/JavaVirtualMachines/$JAVA8/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

# Aliases

alias tig="tig --all"
